name: plantsai
description: Plants AI
publish_to: none 
version: 1.4.2+33

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.29.0

dependencies:
  cached_network_image: ^3.4.1 
  cloud_firestore: ^5.6.5         
  cupertino_icons: ^1.0.8     
  dart_mappable: ^4.4.0        
  device_info_plus: ^11.5.0    
  drift: ^2.25.1
  drift_flutter: ^0.2.4       
  firebase_analytics: ^11.4.4 
  firebase_auth: ^5.5.1        
  firebase_core: ^3.12.1       
  firebase_messaging: ^15.2.4  
  firebase_storage: ^12.4.4    
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4 
  flutter_markdown: ^0.7.3       
  google_mobile_ads: ^6.0.0      
  google_sign_in: ^7.0.0         
  html: ^0.15.4                 
  http: ^1.2.1                  
  image_picker: ^1.1.2          
  path_provider: ^2.1.4         
  provider: ^6.1.2              
  share_plus: ^11.0.0             
  shared_preferences: ^2.3.0 

  shimmer: ^3.0.0               
  url_launcher: ^6.3.0          
  mime: any                  
  purchases_flutter: ^8.6.0   
  purchases_ui_flutter: ^8.6.0 
  font_awesome_flutter: ^10.7.0 
  flutter_animate: ^4.5.2        
  mobile_device_identifier:
    git:
      url: https://github.com/Tughra/mobile_device_identifier.git
      ref: master
  wechat_assets_picker: ^9.5.1 
  wechat_camera_picker: ^4.3.7 
  lottie: ^3.1.2                
  lucide_icons: ^0.257.0        
  flutter_rating_bar: ^4.0.1    
  in_app_review: ^2.0.9         
  loading_indicator: ^3.1.1     
  l10n_flutter: ^1.0.7          
  flutter_localizations:
    sdk: flutter
  intl: any                  
  image_cropper: ^9.1.0         
  cloud_functions: ^5.3.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_gen: ^5.10.0

dev_dependencies:
  build_runner: ^2.4.11         
  dart_mappable_builder: ^4.2.3 
  drift_dev: ^2.25.2         
  flutter_lints: ^6.0.0        
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/logoicon/icon.png
    - lib/moduls/data_jeson/data_Visulisation.json

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/logoicon/icon.png"