name: PlantsAI
description: Plants AI
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.2+18

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.22.2

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.0.1
  cupertino_icons: ^1.0.5
  dart_mappable: ^4.2.2
  device_info_plus: ^10.1.0
  drift: ^2.19.1
  drift_flutter: ^0.1.0
  facebook_app_events: ^0.19.2
  firebase_analytics: ^11.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.7.3
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  html: ^0.15.3
  http: ^1.2.1
  image_picker: ^1.1.2
  path_provider: ^2.0.13
  provider: ^6.0.5
  share_plus: ^9.0.0
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  mime: any
  purchases_flutter: ^6.29.4
  purchases_ui_flutter: ^6.29.4
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.5.0
  mobile_device_identifier: 
    git: 
      url: https://github.com/Tughra/mobile_device_identifier.git
      ref: master
  wechat_assets_picker: ^9.1.0
  wechat_camera_picker: ^4.3.1
  flutter_localizations:
    sdk: flutter
  lottie: ^3.1.2
  lucide_icons: ^0.257.0
  flutter_rating_bar: ^4.0.1
  in_app_review: ^2.0.9
  loading_indicator: ^3.1.1



dev_dependencies:
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
  drift_dev: ^2.19.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/logoicon/icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/logoIcon/icon.png"
